//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEvent
    {
        public System.Guid Id { get; set; }
        public string AppName { get; set; }
        public string EventType { get; set; }
        public string EventDescription { get; set; }
        public string Query { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> rct { get; set; }
        public Nullable<System.DateTime> rut { get; set; }
    }
}
