//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address1 { get; set; }
        public string Street { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<bool> EmailVerified { get; set; }
        public Nullable<bool> IsVerifiedAsBuyer { get; set; }
        public string IP { get; set; }
        public string AccountStatus { get; set; }
        public string ReasonForDeactivation { get; set; }
        public Nullable<int> LinkedAccount { get; set; }
        public string RegistrationSource { get; set; }
        public Nullable<bool> IsSupplier { get; set; }
        public Nullable<bool> IsBulkSupplier { get; set; }
        public Nullable<bool> IsVerifiedAsSupplier { get; set; }
        public Nullable<int> VerifiedBy { get; set; }
        public string Comments { get; set; }
        public Nullable<int> rcb { get; set; }
        public Nullable<int> rub { get; set; }
        public System.DateTime rct { get; set; }
        public Nullable<System.DateTime> rut { get; set; }
    }
}
