//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public Dictionary()
        {
            this.Dictionary1 = new HashSet<Dictionary>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public string Value { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> RCB { get; set; }
        public Nullable<int> RUB { get; set; }
        public Nullable<System.DateTime> RCT { get; set; }
        public Nullable<System.DateTime> RUT { get; set; }
    
        public virtual ICollection<Dictionary> Dictionary1 { get; set; }
        public virtual Dictionary Dictionary2 { get; set; }
    }
}
