//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string ZipCode1 { get; set; }
        public string PlaceName { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
        public string CountyProvince { get; set; }
        public string CountyProvinceCode { get; set; }
        public string Community { get; set; }
        public string CommunityCode { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<int> accuracy { get; set; }
    }
}
